# mobile/scripts/make_ground.py
"""Meadow art -> map ground tiles -> src/map/ground-images.generated.ts.

The map page (a WebView) paints two textures over the Kakao map when zoomed out (DESIGN.md §4.3):
the meadow where fog has cleared, and a pale desaturated meadow as the fog itself.

  python mobile/scripts/make_ground.py MEADOW.png [--preview]

The source is not a seamless tile, so it is mirrored 2x2: edges always meet themselves.
"""
import argparse
import base64
import io
from pathlib import Path

from PIL import Image, ImageOps

HALF = 448  # one quadrant; the tile is 2*HALF css px, about the width of two phone screens
FOG = (0xCA, 0xD7, 0xD1)  # color.fog
MOBILE = Path(__file__).resolve().parents[1]


def tile_of(src):
    side = min(src.size)
    left, top = (src.width - side) // 2, (src.height - side) // 2
    q = src.crop((left, top, left + side, top + side)).resize((HALF, HALF), Image.LANCZOS)
    tile = Image.new("RGB", (HALF * 2, HALF * 2))
    tile.paste(q, (0, 0))
    tile.paste(ImageOps.mirror(q), (HALF, 0))
    tile.paste(ImageOps.flip(q), (0, HALF))
    tile.paste(ImageOps.flip(ImageOps.mirror(q)), (HALF, HALF))
    return tile


def fog_of(tile):
    """The same meadow seen through fog: only its light/dark survives, as a faint pattern on fog grey."""
    grey = ImageOps.autocontrast(tile.convert("L"))
    bands = [grey.point(lambda v, c=c: min(255, round(c * (0.86 + 0.22 * v / 255)))) for c in FOG]
    return Image.merge("RGB", bands)


def data_uri(img, quality):
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=quality, optimize=True)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("meadow")
    ap.add_argument("--preview", action="store_true", help="also write scripts/ground-preview.jpg")
    a = ap.parse_args()

    meadow = tile_of(Image.open(a.meadow).convert("RGB"))
    fog = fog_of(meadow)
    assert meadow.size == fog.size == (HALF * 2, HALF * 2)
    out = MOBILE / "src" / "map" / "ground-images.generated.ts"
    out.write_text(
        "// GENERATED by mobile/scripts/make_ground.py — do not edit by hand.\n"
        f"export const GROUND = {{\n  tile: {HALF * 2},\n  meadow: '{data_uri(meadow, 78)}',\n  fog: '{data_uri(fog, 70)}',\n}};\n",
        encoding="utf-8",
    )
    if a.preview:
        sheet = Image.new("RGB", (HALF * 4, HALF * 2))
        sheet.paste(meadow, (0, 0))
        sheet.paste(fog, (HALF * 2, 0))
        sheet.save(MOBILE / "scripts" / "ground-preview.jpg", quality=80)
    print("wrote", out.name, out.stat().st_size // 1024, "KB")


if __name__ == "__main__":
    main()
