# mobile/scripts/make_cat.py
"""Cat art -> src/map/cat-image.generated.ts (three coats).
  python mobile/scripts/make_cat.py [CAT_IMAGE]
No image -> amber placeholder cat (circle head + ears). Same background handling as make_markers.py.
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageOps

sys.path.insert(0, str(Path(__file__).parent))
from make_markers import AMBER, AMBER_DEEP, MOBILE, SIZE, cut, square  # noqa: E402


def placeholder():
    # ponytail: temporary cat until the user's art arrives — pass an image path.
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(22, 60), (34, 14), (60, 44)], fill=AMBER_DEEP + (255,))
    d.polygon([(106, 60), (94, 14), (68, 44)], fill=AMBER_DEEP + (255,))
    d.ellipse((16, 30, 112, 122), fill=AMBER + (255,))
    for x in (46, 82):
        d.ellipse((x - 6, 66, x + 6, 78), fill=(74, 61, 48, 255))
    return img


def variants(img):
    """One art -> three coats: original = cheese, greyscale = gray, darkened greyscale = black."""
    alpha = img.getchannel("A")
    grey = ImageOps.grayscale(img.convert("RGB"))
    coat = lambda l: Image.merge("RGBA", (l, l, l, alpha))  # noqa: E731
    return {"cheese": img, "gray": coat(grey), "black": coat(grey.point(lambda v: int(v * 0.35)))}


img = square(cut(sys.argv[1], 18)) if len(sys.argv) > 1 else placeholder()
lines = [
    "// GENERATED by mobile/scripts/make_cat.py — do not edit by hand.",
    "import type { CatColor } from './catColors';",
    "",
    "export const CAT_IMAGES: Record<CatColor, string> = {",
]
for name, v in variants(img).items():
    buf = io.BytesIO()
    v.save(buf, "PNG", optimize=True)
    lines.append(f"  {name}: 'data:image/png;base64,{base64.b64encode(buf.getvalue()).decode()}',")
lines.append("};")
(MOBILE / "src" / "map" / "cat-image.generated.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote cat-image.generated.ts (cheese, gray, black)")
