# mobile/scripts/make_cat.py
"""Cat art -> src/map/cat-image.generated.ts.
  python mobile/scripts/make_cat.py [CAT_IMAGE]
No image -> amber placeholder cat (circle head + ears). Same background handling as make_markers.py.
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).parent))
from make_markers import AMBER, AMBER_DEEP, MOBILE, SIZE, cut, square  # noqa: E402


def placeholder():
    # ponytail: temporary cat until the user's art arrives — pass an image path.
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.polygon([(22, 60), (34, 14), (60, 44)], fill=AMBER_DEEP + (255,))
    d.polygon([(106, 60), (94, 14), (68, 44)], fill=AMBER_DEEP + (255,))
    d.ellipse((16, 30, 112, 122), fill=AMBER + (255,))
    for x in (46, 82):
        d.ellipse((x - 6, 66, x + 6, 78), fill=(74, 61, 48, 255))
    return img


img = square(cut(sys.argv[1], 18)) if len(sys.argv) > 1 else placeholder()
buf = io.BytesIO()
img.save(buf, "PNG", optimize=True)
(MOBILE / "src" / "map" / "cat-image.generated.ts").write_text(
    "// GENERATED by mobile/scripts/make_cat.py — do not edit by hand.\n"
    f"export const CAT_IMAGE = 'data:image/png;base64,{base64.b64encode(buf.getvalue()).decode()}';\n",
    encoding="utf-8",
)
print("wrote cat-image.generated.ts")
